version: "3.8"

services:

  postgres:
    image: postgres:14
    container_name: pricing-postgres
    environment:
      POSTGRES_DB: pricingdb
      POSTGRES_USER: siddheshbahety
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: pricing-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: pricing-app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"