spring:
  application:
    name: pricing-engine

  datasource:
    url: jdbc:postgresql://postgres:5432/pricingdb
    username: siddheshbahety
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  logging:
    level:
      root: INFO
      com.siddhesh.pricingengine: DEBUG

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

pricing:
  model:
    version: v1
    base-multiplier: 1.0

  demand:
    high-threshold: 0.8
    low-threshold: 0.3

  surge:
    max-multiplier: 2.5
    min-multiplier: 0.8

  cache:
    ttl-seconds: 300